apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: aggregator-service
  name: aggregator-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: aggregator-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - image: aditya9827/test-repo-k8s:aggregator-service.0.0.2 #CHANGE
        imagePullPolicy: IfNotPresent
        name: aggregator-service
        env:
          - name: USER_SERVICE_URI
            value: http://user-service
          - name: ORDER_SERVICE_URI
            value: http://order-service
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: aggregator-service
  name: aggregator-service
  namespace: default
spec:
  ports:
  - # nodePort: 30701 #CHANGE
    port: 8083 #CHANGE
    protocol: TCP
    targetPort: 8083 #CHANGE
  selector:
    app: aggregator-service
  sessionAffinity: None #CHANGE
  type: LoadBalancer