apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: order-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - image: aditya9827/test-repo-k8s:order-service.0.0.6 #CHANGE
        imagePullPolicy: IfNotPresent
        name: order-service
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: order-service
  name: order-service
  namespace: default
spec:
  ports:
  - # nodePort: 30701 #CHANGE
    port: 8081 #CHANGE
    protocol: TCP
    targetPort: 8081 #CHANGE
  selector:
    app: order-service
  sessionAffinity: None #CHANGE
  type: ClusterIP